# Generated by Django 3.2 on 2023-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_remove_news_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_af',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar_dz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ast',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_be',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_br',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ca',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_da',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_dsb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_el',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_au',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_gb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_co',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_mx',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ni',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ve',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_et',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ga',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gd',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_he',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hsb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hu',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ig',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ind',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_io',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_is',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ja',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kab',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_km',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lv',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ml',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_my',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nb',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_os',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pa',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr_latn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sw',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ta',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_te',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_th',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_udm',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_af',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ar_dz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ast',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_be',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_br',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_bs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ca',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_cs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_cy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_da',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_dsb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_el',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_au',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_gb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_co',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_mx',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ni',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es_ve',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_et',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ga',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gd',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_he',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hsb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hu',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ig',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ind',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_io',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_is',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_it',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ja',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ka',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kab',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_km',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ko',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_lv',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ml',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_mr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_my',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nb',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ne',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_nn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_os',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt_br',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ro',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sq',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sr_latn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sv',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_sw',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ta',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_te',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_th',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_udm',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ur',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_vi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hans',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh_hant',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
